### ISSUE TITLE
DISTINCT missing

### ISSUE THREAD

**Issue by lavermil** [Azure/azure-stream-analytics#121]
Hello,

I am trying to parse through Azure NSG Diagnostic records in the Event Hub stream. I am not finding a DISCTINCT function available and am not sure how I would be able to return a unique list.

For example I am trying to get a unique list of resourceIds from the Azure NSG Diagnostic records in the Event Hub stream.

I am using this to query to get the resourceId only to return but I have the resourceId returned for each record and only want the DISTINCT/unique list returned.

```
WITH Temp AS (
SELECT
    AR.ArrayValue.resourceId
FROM
    [azurelogs] as al
CROSS APPLY GetArrayElements(al.records) as AR
)

Select resourceId into [outputalias] from Temp
```

Thank you in advance.

**Comment by Fleid** [comment]
We don't support the DISTINCT keyword because it comes with no explicit grouping clause in T-SQL (even though you are basically grouping by all the keys used in the projection). In stream processing you will need to at least group by a [time window](https://docs.microsoft.com/en-us/stream-analytics-query/windowing-azure-stream-analytics?toc=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fazure%2Fstream-analytics%2Ftoc.json&bc=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fazure%2Fbread%2Ftoc.json). 

So you will need to explicitly GROUP BY your keys and a time window, to obtain a distinct list, at which point you don't need to use the DISTINCT keyword anymore.

Of course that means you need to tell us what is the time period over which to calculate the distinct list (below every 5 minutes).

```SQL
WITH Temp AS (
SELECT
    AR.ArrayValue.resourceId
FROM
    [azurelogs] as al
CROSS APPLY GetArrayElements(al.records) as AR
),
DistinctValues AS (
SELECT
    System.Timestamp() AS WindowEnd,
    resourceId
FROM Temp
GROUP BY resourceId, Tumbling(minute,5)
)

Select WindowEnd, resourceId into [outputalias] from DistinctValues
```
If you need to maintain an absolute list of values, you will need to do that downstream (ASA doesn't have a storage layer), either via [Upsert ](https://docs.microsoft.com/en-us/azure/stream-analytics/stream-analytics-documentdb-output#upserts-from-stream-analytics)mode into Cosmos DB, or using a [technique ](https://docs.microsoft.com/en-us/azure/stream-analytics/sql-database-upsert)to replicate the behavior in Azure SQL.

**Comment by lavermil** [comment]
I am not sure if what you provided was supposed to be a working example. It has the following error.

`GROUP BY with no aggregate expressions is not supported.`

I added a `COUNT(*)` to the DistinctValues `SELECT` as the aggregate expression and it worked.

I am interested in do thing over a 30 day set of records. Tumbling only supports 7 days. :(

If I set the Tumbling to 7 days then it I will get the unique resourceIds within a 7 day period. This would basically limit my ability to generate a DISTINCT/unique list from only 7 days worth of records. 

Is that correct?

**Comment by Fleid** [comment]
Good catch with the aggregate expressions, I had forgotten about that.

But yes, if you want to calculate distinct values in the stream, then it will need to be time windowed. This is not specific to Stream Analytics, but to all stream processors. They operate on unbounded data (we never know when the stream will stop, if ever), so you need to put a limit in the query. For technical reasons, we limit these windows at 7 days (this is already a lot).

If you need 30 days, you will need to upsert your results in a table with the Id and Week as keys.
