### ISSUE TITLE
Cannot read data from Azure's EventHub sample project.

### ISSUE THREAD

**Issue by DavePilks** [Azure/azure-stream-analytics#21]
I have the EventHub sample project running that writes to to an EventHub instance like this:

```
var message = $"Message {i}";
Console.WriteLine($"Sending message: {message}");
var eventData = new EventData(Encoding.UTF8.GetBytes(message));
eventData.Properties["EventType"] = "Test";
await  sender.SendAsync(eventData);
```

But when I try to connect Stream Analytics to this, I get the following issue:

> Could not deserialize the input event as Json. Some possible reasons: 1) Malformed events 2) Input source configured with incorrect serialization format

I can read from the stream with no issue. So why cant Stream Analytics? As you can see, the body is a simple string that is `UTF8` encoded.

**Comment by jeffstokes72** [comment]
@DavePilks hello! Which specific project are you mentioning so I can direct this appropriate? Apologies for the delay.

Jeff

**Comment by mefree98** [comment]
I too am having this same problem.  My stream analytics worked fine using the .wpf application.  I've since tried to use the .NetCore version of the twitter data generator which says I have to change to use compression, which I've done in Gzip with JSON and every delimiter type, same issue.  I even tried using .avro and the same issue occurs.  Is there documentation on how to properly configure the stream analytics to work with the .NetCore twitter generator?

**Comment by Fleid** [comment]
Closing stale issues
