### ISSUE TITLE
Cannot cast value of type 'array' to type 'record'

### ISSUE THREAD

**Issue by mouhannadali** [Azure/azure-stream-analytics#95]
I am trying to integrate Azure Stream Analytics with Azure Machine Learning and getting the following error:
I am getting the following error:
**` Cannot cast value of type 'array' to type 'record' in expression 'inputArray'. At line '7' and column '18'. TRY_CAST function can be used to handle values with unexpected type.
`**
- steps:
I have deployed an azureml model in aks and linked the model to Azure Stream Analytics
![image](https://user-images.githubusercontent.com/17967903/121002810-0b5ea400-c78d-11eb-9921-c0e806768fd0.png)

the model input was defined as the following:
```
input_sample = np.array([[34.13,34.13,34.13,34.13,3.48,34.13,34.13,34.13,34.13,34.13,34.13]])
@input_schema('data', NumpyParameterType(input_sample))
```

in Azure Stream Analytics I created an input array
```
function createArray(v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11) {
    'use strict';
    var array = [v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11]
    return array;
}
```

and when I am trying to invoke the  Azure Machine Learning UDF using the following query:
```
WITH 
ModelInput AS (
SELECT udf.createArray(cast(v1 as float), cast(v2 as float), cast(v3 as float), cast(v4 as float), cast(v5 as float), cast(v6 as float), cast(v7 as float), cast(v8 as float), cast(v9 as float), cast(v10 as float), cast(v11 as float)) as inputArray
FROM input
) 

SELECT udf.score(inputArray)
INTO output
FROM ModelInput
WHERE inputArray is not null
```

I am getting the following error:
` Cannot cast value of type 'array' to type 'record' in expression 'inputArray'. At line '7' and column '18'. TRY_CAST function can be used to handle values with unexpected type.
`

**Comment by Fleid** [comment]
Hi @mouhannadali,

Could you please check that the createArray works properly by testing the query against a sample (either in the portal or VSCode).

```SQL
WITH ModelInput AS (
	SELECT udf.createArray(cast(v1 as float), cast(v2 as float), cast(v3 as float), cast(v4 as float), cast(v5 as float), cast(v6 as float), cast(v7 as float), cast(v8 as float), cast(v9 as float), cast(v10 as float), cast(v11 as float)) as inputArray,
	*
	FROM input
)

SELECT *
FROM ModelInput
```
If this indeed returns an array, then we'll need to look into udf.score and understand why it's not taking it.

**Comment by sidramadoss** [comment]
Hi @mouhannadali - please also share a link to your swagger definition.

**Comment by mouhannadali** [comment]
HI @Fleid and @sidramadoss 

the query you send it return the following:
![image](https://user-images.githubusercontent.com/17967903/121209355-12fc7680-c87b-11eb-9721-4b7674081a0b.png)

reducing the input data to 1 row, the json output is:
[{"inputArray":[-2,1.51,10.14,0,0,0,-15.78,-22.31,-11.7,-13.57,92.95],"v1":"-2","v2":"1.51","v3":"10.14","v4":"0","v5":"0","v6":"0","v7":"-15.78","v8":"-22.31","v9":"-11.7","v10":"-13.57","v11":"92.95"}]


and in the scoring script, I have commented out the model and returning fixed value as list [5.0]

link to swagger file
http://20.71.72.91/api/v1/service/anomalydemo/swagger.json

**Comment by sidramadoss** [comment]
You have specified sample input as an array and the return as a float. So when you return a hard coded value in your scoring script, it should be a float. because you are returning a list now, its type doesnt match the expected float. You can use this as reference: https://github.com/Azure/azure-stream-analytics/blob/master/Samples/AzureML/score.py

To validate, please use Postman to create a sample request with the payload you mentioned above (of 1 array), and see if the response you get matches exactly what is expected.

**Comment by Fleid** [comment]
Looks like the input is an object containing an array called `data`, and not just an array:

```JSON
"ServiceInput": {"type": "object", "properties": {"data": {"type": "array", "items": {"type": "array", "items": {"type": "number", "format": "double"}}}}, "example": {"data": [[34.13, 34.13, 34.13, 34.13, 3.48, 34.13, 34.13, 34.13, 34.13, 34.13, 34.13]]}}, 
"ServiceOutput": {"type": "array", "items": {"type": "number", "format": "double"}, "example": [13.66304196]},
```

ServiceOutput is an array, ServiceInput is not. The example also shows that: 
` {"data": [[34.13, 34.13, 34.13, 34.13, 3.48, 34.13, 34.13, 34.13, 34.13, 34.13, 34.13]]}` 
instead of : `[34.13, 34.13, 34.13, 34.13, 3.48, 34.13, 34.13, 34.13, 34.13, 34.13, 34.13]`.

You can either build that object in your UDF in ASA, or change your service definition.

**Comment by mouhannadali** [comment]
I have tested on postman and it is working 
and I am using the same output as the example you have provide
output_sample = np.array([13.66304196])
@output_schema(NumpyParameterType(output_sample))

and in your example you return 
`return result.tolist()
`and in my case I am returning 
 result = np.around([5.37])
`return result.tolist()
`
I have tried to change the input to pandas:
```
def pandas_sample_input():
    pandas_input_data = {'v1': pd.Series([34.13]), 'v2': pd.Series([34.13]), 'v3': pd.Series([34.13]), 'v4': pd.Series([34.13]), 'v5': pd.Series([34.13]), 'v6': pd.Series([34.13]), 'v7': pd.Series([34.13]), 'v8': pd.Series([34.13]), 'v9': pd.Series([34.13]), 'v10': pd.Series([34.13]), 'v11': pd.Series([34.13])}
    return pd.DataFrame(data=pandas_input_data)
```

`@input_schema('df', PandasParameterType(pandas_sample_input(), orient='records'))
` 
and changed the query as:
```
WITH 
Dataframe AS (
SELECT cast(v1 as float) v1,cast(v2 as float) v2,
cast(v3 as float) v3,cast(v4 as float) v4,cast(v1 as float) v5,
cast(v6 as float) v6,cast(v7 as float) v7,cast(v8 as float) v8,cast(v9 as float) v9,cast(v10 as float) v10,cast(v11 as float) v11
FROM input
) 

SELECT udf.score(Dataframe)
INTO output
FROM Dataframe
```
and swagger link:
http://20.71.72.91/api/v1/service/anomalydemo/swagger.json

It worked if I have one raw as input but I have multi raw then get:
Unexpected number of results returned by callout.

**Comment by sidramadoss** [comment]
When sending one input array as part of http request to the endpoint, it returns the right result:
![image](https://user-images.githubusercontent.com/38441940/121226474-74065900-c83f-11eb-8ac5-18eb02c42367.png)

The problem is with how your endpoint handles multiple inputs part of the same input. If 2 arrays are sent as part of the same http request, the expectation is that there are equal number of results in the response from endpoint. I tried sending 2 arrays but got only 1 result which doesn't make sense.
![image](https://user-images.githubusercontent.com/38441940/121226396-5cc76b80-c83f-11eb-807c-31c9d8564e1c.png)

**Comment by mouhannadali** [comment]
@Fleid thanks for the update, is there a way to send x raws and get one output?

**Comment by sidramadoss** [comment]
> Looks like the input is an object containing an array called `data`, and not just an array:
> 
> ```json
> "ServiceInput": {"type": "object", "properties": {"data": {"type": "array", "items": {"type": "array", "items": {"type": "number", "format": "double"}}}}, "example": {"data": [[34.13, 34.13, 34.13, 34.13, 3.48, 34.13, 34.13, 34.13, 34.13, 34.13, 34.13]]}}, 
> "ServiceOutput": {"type": "array", "items": {"type": "number", "format": "double"}, "example": [13.66304196]},
> ```
> 
> ServiceOutput is an array, ServiceInput is not. The example also shows that:
> ` {"data": [[34.13, 34.13, 34.13, 34.13, 3.48, 34.13, 34.13, 34.13, 34.13, 34.13, 34.13]]}`
> instead of : `[34.13, 34.13, 34.13, 34.13, 3.48, 34.13, 34.13, 34.13, 34.13, 34.13, 34.13]`.
> 
> You can either build that object in your UDF in ASA, or change your service definition.

ASA actually takes care of constructing 'data' by inferring it from the swagger. so no need to do this. @mouhannadali - please see my explanation above. that should solve your problem. If you are still experiencing issues, please create a support ticket or email askasa@microsoft.com

**Comment by mouhannadali** [comment]
@sidramadoss thanks for the update, is there a way to send x raws and get one output?

**Comment by sidramadoss** [comment]
No. That doesn't make sense from a streaming perspective. When your job runs and processes data in real time, it does 'adaptive batching', where it groups N number of data points/payload as part of 1 http request that gets sent to the ml endpoint (instead of doing N http requests serially). Therefore for N input events, it needs N results.

**Comment by mouhannadali** [comment]
@sidramadoss thanks for the clarification. ASA and its logic are new for me. I was it should support that to predict something you might need some history.
